name: "Build main branch to chromatic"

on:
  pull_request_target:
    types:
      - closed
    branches:
      - feature/*
    paths:
      - "src/**.ts(x)"
      - "src/**.css"
      - "src/stories/**/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic:
    # Run only if the closed PR was merged
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/chromatic.yml
    secrets:
      # 👇 Chromatic projectToken, refer to the manage page to obtain it.
      projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
