name: "Build feature branch to chromatic"

on:
  push:
    branches:
      - feature/*
  pull_request_target:
    types:
      - opened
      - edited
    branches:
      - feature/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic:
    uses: ./.github/workflows/chromatic.yml
    secrets:
      # 👇 Chromatic projectToken, refer to the manage page to obtain it.
      projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
